### ISSUE TITLE
Discord crashes upon using SHIFT+ENTER shortcut.

### ISSUE THREAD

**Issue by officialxinc** [joe27g/EnhancedDiscord#159]
I saw another post on another site talking about Better Discord's Canary being broken telling people to replace a file with another file but this isn't better discord, so I don't know what's going on, also the discord invite link on your website isRO invalid.

**Comment by Corrupt-Specturion** [comment]
![image](https://user-images.githubusercontent.com/54480005/110045850-f0edd800-7d10-11eb-99ac-89dee6b4988b.png)
They might not fix it going off of ^
My Discord crashes when right clicking as well as hitting shift-enter

**Comment by officialxinc** [comment]
The thing that confuses me, is it doesn't happen to my friends discord, he's able to use it and there aren't any problems. I asked him to try to do shift-enter and he said nothing happened.

**Comment by gowonsie** [comment]
yeah, I had to uninstall it completely, my friend who uses BetterDiscord has this same problem. I'm just going to wait until they fix it or just stick with normal discord if they can't fix it. It's still disappointing nonetheless.

**Comment by rauenzi** [comment]
This was fixed on BD in January, users just need to reinstall.

**Comment by Corrupt-Specturion** [comment]
> 
> 
> This was fixed on BD in January, users just need to reinstall.

Reinstall ED or Discord itself? Because after I reinstalled ED, it still crashed when pressing shift + enter.

**Comment by rauenzi** [comment]
I was referring to BD as I said.

**Comment by Corrupt-Specturion** [comment]
Oh. I took that to mean it also worked for ED.

**Comment by FeelsBadMan1** [comment]
I have the same issure and im not sure how to solve this.

**Comment by januaryguy** [comment]
Same, it's quite frustrating and I dont really want to move off to better discord. Enhanced discord fulfills everything I need and isn't really in the way.

**Comment by FeelsBadMan1** [comment]
> Same, it's quite frustrating and I dont really want to move off to better discord. Enhanced discord fulfills everything I need and isn't really in the way.

well i solved it for me. If anyone else has this error then do following steps:

1. copy plugins & themesfolder to another dictonary so you not need to redownload them if you have some except the standard
2. uninstall EnhancedDiscord
3. Install again, cklick on otp devmode and wait for it to be installed, then open setup again and update & then reinject.
4. Launch EnhancedDiscord and it will be fixed. Howwever ti will tell you that your message is too long while its mabe only 2 words. but you still can send them.

**Comment by a3a3aikarus** [comment]
easy fix is runnig `global.onerror = null;` in dev console or creating/modifying plugin/dom_sht.js with it

**Comment by MasicoreLord** [comment]
Partially fixed by last update, and EnhancedDiscord has cut off updates, and all remaining official support will terminate April 12th.
